# 表名称
tablename:
  BatchInfo: "batchinfo"                                      # 批上传数据表
  BatchMaterialUniform: "batch_material_uniform_vector"       # 批数据向量表
  MaterialInfo: "ProductData"                                 # 主数据表
  MaterialUniform: "material_uniform_vector"                  # 主数据向量表
  MateialBatchResult: "material_batch_result"                 # 结果存储表
  StrReplaceInfo: "SpecialCharacters"                         # 字符替换表

# 基础变量
basevariable:
  similarthreshold: 0.98  # 默认相似度阈值
  startmp_threshold: 50  # 默认开启多进程计算向量的阈值
  core_process: 4         # 默认多进程核心数
  filterCondition: 0      # 筛选数据的条件
  limitnum: None          # 限制数据输出的条数
  expireTime: 120000      # redis中存储数据过期时间


# DB数据库
# '192.168.192.137'  测试环境
# '192.168.192.145'  生产环境
database:
  mssql:
    url: "mssql+pymssql://sa:Bkdsj509@1.1.4.46:1433/zhjtest01?charset=utf8"
#    url: "mssql+pymssql://sa:root@1.1.4.66:1433/zhjtest01?charset=utf8"
  mysql:
    url: "mysql+pymysql://root:123456@192.168.192.146:3306/db_onlymaterial_businessflow?charset=utf8"
  redis:
    config:
      host: "1.1.4.46"
      port: 6379
      db: 2    # 数据库号，默认1号
      pwd: 123456
  localcsv:
    url: ""

path: #本地路径
  log_path: 'H:\Project\pythonworkspace\ZHJ-YIPIN-X\ZHJYipinBusisness\logs\yipin.log' #日志路径